version: '3'
services:

  nginx-proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APPLICATION}:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    links:
      - php
    networks:
      - docker-network

  php:
    container_name: php7.4-fpm
    restart: always
    image: php7.4-fpm
    build:
      dockerfile: php7.4-fpm.dockerfile
      context: ./docker-files/
      args:
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
        - INSTALL_OCI8_PDO_ORACLE=${PHP_FPM_INSTALL_OCI8_PDO_ORACLE}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
        - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
        - INSTALL_NPM=${PHP_FPM_INSTALL_NPM}
    expose:
      - "9000"
    volumes:
      - ${APPLICATION}:/var/www/html/
      - ${PHP_INI}:/usr/local/etc/php/php.ini
    links:
      - mysql
    networks:
      - docker-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql8
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_CONF}:/etc/mysql/conf.d
      - ${MYSQL_LOG}:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - docker-network

networks:
    docker-network:
        driver: bridge
